language: python

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      python: 3.7.2
      services:
      - docker
      env: CIBW_BEFORE_BUILD="rm -rf build/" CIBW_TEST_COMMAND="python3 {project}/setup.py test"
    - os: osx
      language: generic

install:
  - pip3 install setuptools
  - pip3 install -e .

script:
  - python3 setup.py test

env:
  global:
    - TWINE_USERNAME="<YOUR_PYPI_USERNAME>"
    # - secure: <YOUR_ENCRYPTED_PYPI_PASSWORD>

before_deploy:
  - pip3 install -r deploy-requirements.txt
  - cibuildwheel --output-dir dist
  - python3 setup.py sdist --dist-dir dist

deploy:
  provider: script
  script: "twine upload --skip-existing dist/*"
  skip_cleanup: true
  on:
    tags: true
