environment:
  TWINE_USERNAME: Tobotimus
  TWINE_PASSWORD:
    secure: TxxQiEl0gowjnWGcxrmNVA==

install:
  - pip install -e .

before_build:
  - pip install -r deploy-requirements.txt

build_script:
  - cibuildwheel --output-dir dist

artifacts:
  - path: "dist\\*.whl"
    name: Wheels

deploy_script:
  - ps: |
      If ($env:APPVEYOR_REPO_TAG -eq "true") {
          & twine upload --skip-existing dist/*.whl
      }
